// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:f73ba65a-9948-4749-bf6e-80245eda7c46',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'client-hosting-mobilehub-1899159748',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd13mn7z0cwkaat.cloudfront.net',
    'aws_mobile_analytics_app_id': '468002de8a354876a6c7654a1ad387b4',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '39f09147-b7a8-4ba9-a9de-49625a1a59c2',
    'aws_project_name': 'client-2018-02-03-13-15-54',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'client-mobilehub-1899159748',
}

export default awsmobile;
